spring:
  application:
    name: audit-service

  config:
    import: optional:configserver:http://config-server:8888

  datasource:
    url: jdbc:mysql://mysql-audit:3306/audit_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      group-id: audit-service-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka